spring:
  # 使用哪个配置文件
  profiles:
    active: devhz
  application:
    name: training-platform

# 端口
server:
  port: 2029
  servlet:
    context-path: /training/platform
  compression:
    enabled: true
    mime-types: application/json

# eureka client 配置
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#mybatis-plus
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法(XML 中有自定义实现)，需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
  mapper-locations:
    classpath*:/mapper/*Mapper.xml
  # 如果不加这个配置，就会对对象里的属性进行过滤，默认field-strategy为NOT_NULL（表示对象属性为null时，不会对该表字段进行更新操作）
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      # 表名是否使用驼峰转下划线命名,只对表名生效
      table-underline: true

#log4j2
logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: debug